language: ruby
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
sudo: false
before_script: bundle update
script: script/cibuild
branches:
  only:
    - master
    - gh-pages
