language: ruby
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
sudo: false
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/build
  - chmod a+x script/cibuild
  - chmod a+x script/scan
  - chmod a+x script/server
  - chmod a+x script/test
  - bundle update
script: script/cibuild
branches:
  only:
    - gh-pages
